<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    
    <OutputPath>bin\$(Platform)\$(Configuration)\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoCAD.NET.Core" Version="24.2.0" />
    <PackageReference Include="AutoCAD.NET" Version="24.2.0" />
    <PackageReference Include="AutoCAD.NET.Model" Version="24.2.0" />
    
    <PackageReference Include="Civil3D.NET" Version="13.4.113" />

    <Reference Include="System" />
    <Reference Include="System.Core" />
  </ItemGroup>

  <PropertyGroup>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
  </PropertyGroup>

</Project>
