name: Build Civil 3D Plugin

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 1. Descarga tu código (con la carpeta /lib incluida)
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Configura msbuild (el compilador de .NET Framework)
    - name: Setup .NET Framework (msbuild)
      uses: microsoft/setup-msbuild@v1

    # 3. Compila el proyecto
    #    Ya no necesita 'nuget restore', solo compilar
    - name: Build project
      run: msbuild ${{ github.workspace }}\Civil3D_Phase1.csproj /p:Configuration=Release /p:Platform=AnyCPU

    # 4. Sube la DLL
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Civil3D-Phase1-DLL
        path: ${{ github.workspace }}\bin\Release\Civil3D_Phase1.dll
